### PR TITLE
Use theme.json

### LINKED ISSUE #73: Request For Comment: Content Widths and Child Themes
# Problem To Solve

We would like the default content width and wide content widths to be different on Creepy Catalog.

So far those two values ( 32rem and 64rem respectively ) have been set in the parent theme and reused as LESS variables in the child themes.

We believe slightly wider default paragraphs that allow for more words per line would be a better reading experience on Creepy Catalog. In discussion with editorial and sales, it was also expressed that we would use the wide width for more images if the difference in size wasn't as large. A goal might be: make sure its possible to see the whole image and fit a caption or heading on screen at the same time on landscape tablets or laptops.

On the otherhand, we do not want to change these values for Shop Catalog where we need the wide width to be large for displaying a grid of products.

So, how could we make it possible for child themes to either inherit the parent theme widths, or change them for their specific needs?

# Context Regarding Theme Settings

In WordPress 5.8, the theme.json file was introduced to partially replace the use of `add_theme_supports` for block editor settings. Adding theme.json is a step toward Full Site Editing which is a long term goal of WordPress where the block editor can used to edit... the full site.

https://make.wordpress.org/core/2021/06/25/introducing-theme-json-in-wordpress-5-8/

## How It's Related

There is a "layout" setting in theme.json that lets you set`contentWidth` and `wideWidth`. Those sizes are applied to the block editor. It is up to the theme developer to apply those values on the front-end.

https://developer.wordpress.org/block-editor/how-to-guides/themes/theme-json/#settings

## Issues With That

- Just adding a theme.json file changes the markup of some blocks. For example the group block loses it's `__inter-container` element which we rely on in some of our CSS.
- Adding a layout setting to your theme.json lets the editor know that you support `__experimentalLayout` features. This allows authors to change the content and wide width settings within group blocks. That's all well and good except the related CSS forces a centered layout.
  - I opened an issue with WordPress about that.
  - We can remove support for __experimentalLayout in the group block through our theme functions file.
- Child themes do not inherit theme.json settings from their parent. They have to have their own file.
- The layout settings values are not made available to the theme on the front-end through CSS custom proprties the way font size, colors and gradients are.
  - We can work around that by adding the layout sizes to CSS custom properties ourselves. I've done that in the `0.6.0-beta1` tag: https://github.com/thoughtis/cata/blob/0.6.0-beta1/theme.json

### References
- https://github.com/WordPress/gutenberg/blob/%40wordpress/block-library%404.0.0/packages/block-library/src/group/edit.js#L87
- https://github.com/WordPress/gutenberg/blob/%40wordpress/block-library%404.0.0/packages/block-library/src/group/edit.js#L33
- https://core.trac.wordpress.org/ticket/53748
- https://core.trac.wordpress.org/browser/tags/5.8/src/wp-includes/class-wp-theme-json-resolver.php#L349

# Options

## Option A - Use Theme.json

- Add theme.json to Cata theme and all child themes.
- Set layout and font sizes in all themes.
  - Optionally set colors and gradients. Not all child themes support them.
- Update all theme CSS to use latest block markup
  - Ex: no `*__inner-container` block in groups.
- Make Content Width and Wide Width available as custom CSS properties.
- Use those custom properties through parent and child themes.

### Pros
- Get on board with the latest WordPress updates.
- Theme.json is more convenient than add_theme_support for fonts, colors, and gradients.
- Font Family support coming soon which we want too.

### Cons
- More work since all themes need to be updated.

## Option B - Use Customizer

- Add settings to the Customizer for Content Width and Wide Width to Cata theme.
- Make those values available as CSS custom properties in admin and front-end.
- Apply those values to the editor using editor-styles.
- Apply those values to the front-end through the parent and child themes.

### Pros
- Less work now because there's less updating in child themes.

### Cons
- Creates tech debt because we will still need to update for WP eventually.

### LINKED ISSUE #74: Set Content Widths in Child Themes
Based on #73 here is my plan

- Expand on the work in https://github.com/thoughtis/cata/tree/0.6.0-beta1 which added theme.json
- Use variables like `--wp--custom--content-size` in CSS in addition to the editor.
- Update existing block CSS to support the latest block markup in WP 5.8
  - Test whether backward compatibility is necessary.
- In child themes
  - Set font sizes, color palette and gradients in theme.json instead of using `add_theme_support`
  - Update CSS to use custom properties for width where desired ( we may still need the old widths for some pages, that's OK ).
  - Update CSS for latest block markup.

### PR DESCRIPTION
**Pull request by douglas-johnson**
### Related Issues

- Closes #74

### What Was Accomplished

- Added `theme.json` which includes font sizes and content widths for the WordPress editor.
- Removed several uses of `add_theme_support` for settings that can be set in `theme.json`
- Removed block modifier classes like `has-*-font-size` that are now produced automatically by WordPress based on `theme.json`
- Updated `wp-block-group` to remove `inner-container` since its no longer available once `theme.json` is enabled.
- Updated `wp-block-columns`, `wp-block-cover`, `wp-block-media-text` so that their layout does not include media queries.
  - **Any desired media queries for these blocks are now the responsibility of the child theme.**
- Updated `wp-block-gallery` to use flexbox and `calc()` to produce suitable layouts based on the number of requested columns and the available width in the `--wp--custom--*-size` custom properties.
  - This is nearly identical to Shop Catalog's styles for the WooCommerce product grid block, except we allow `flex-grow` here because we're not specifically making a grid.
- Added `Core_Group` PHP class to remove support for `__experimentalLayout` from groups until the issues with centering that we described in #73 are resolved.
- Removed `Core_Button` PHP class since the borderRadius setting it modified has been moved and it not accessible without the Gutenberg plugin at the moment.

### How To Test

- [x] In local development site, block editor is operational and works as expected.
- [x] Content for group, columns, cover, and media-text is output as expected, though not necessarily 100% responsive.
- [x]  `wp-block-gallery` works as expected and is responsive.
- [x] When editing a group, no content width options are shown.

### CODE REVIEW

**Comment by douglas-johnson** [comment]
@richdacuban You don't need to review these other pull requests individually ( they're all very similar ), but I wanted to you to see how this is being rolled out to the child themes.

https://github.com/thoughtis/wpe-creepycatalog/pull/206
https://github.com/thoughtis/wpe-thoughtfulhome/pull/25
https://github.com/wpcomvip/shopcatalog/pull/628

**Review by richdacuban — APPROVED** [review]
Columns are not displayng side by side:
Screen Shot 2021-08-09 at 4 10 14 PM
Columns are somewhat responsive
Screen Shot 2021-08-09 at 4 13 04 PM
Screen Shot 2021-08-09 at 4 13 39 PM
Cover blocks are outputting without bg color 
Screen Shot 2021-08-09 at 4 14 17 PM
Screen Shot 2021-08-09 at 4 16 44 PM


If these are as expected, then it is working!

**Comment by douglas-johnson** [comment]
@richdacuban That `vivid-red` background color is part of the default WordPress palette, which we disable. Is that color available in the editor for you, or is it from preexisting content?

**Comment by richdacuban** [comment]
> @richdacuban That `vivid-red` background color is part of the default WordPress palette, which we disable. Is that color available in the editor for you, or is it from preexisting content?

I can set colors for a cover block in the cata editor. The color is outputted on the front end as a class `has-x-background-color` but the actual displayed output on the front end is always black.


Screen Shot 2021-08-10 at 10 20 11 AM
Screen Shot 2021-08-10 at 10 20 18 AM
Screen Shot 2021-08-10 at 10 20 24 AM
Screen Shot 2021-08-10 at 10 20 35 AM
Screen Shot 2021-08-10 at 10 21 17 AM
Screen Shot 2021-08-10 at 10 21 49 AM
Screen Shot 2021-08-10 at 10 22 05 AM

**Comment by douglas-johnson** [comment]
The default palette was being displayed because of a verison mismatch. The minimum WordPress version for Cata is now 5.8 since that's when theme.json support started.

**Pull request merged**
