### PR TITLE
Updates for WordPress 5.9

### PR DESCRIPTION
**Pull request by douglas-johnson**
### What Was Accomplished
- Rename "Huge" font size to "Extra Large" per WP recommendation.
- Added line-height for `.has-x-font-size` block modifier class.
- Updated layout styles for Button, Columns / Column and Gallery blocks.
 - Columns now uses 3 as it's default number of columns.
 - Gallery no longer has a list element inside it to control layout. It's just a block with image blocks inside.
- Removed our layout for Button**s** because it is done inline by WordPress now.
- Removed our own styles for the Cover block in favor of using the WordPress default styles.
  - Todo in child themes: override `.is-dark` color selection behavior where necessary.
- Removed our lack of support for `__experimentalLayout`
  - The issue we filed about how it centers everything is still relevant, but without it, aligning grouped content just doesn't work right.
- Removed support for `__experimentalBorder` from buttons and pull quotes since it's only half implemented.
- Added support for `__experimentalFontFamily` since it is implemented for blocks typically used in Full Site Editing, but we really want to use it for paragraphs and headings.
  - Todo in child themes: add font family configurations in the theme.json file and add actual font files for use in the editor.
- Added a filter on `block_render` for columns which adds `has-relative-units` or `has-static-units` CSS classes based on the units being used.
  - This gives devs more strict control of flex wrapping when using rem or em units, while leaving percentages available to use when you want breakpoints rather than instrinsic sizing.
  - "static" = any column has a unit other than percentage.
  - "realtive" = all columns use percentages or no flex-basis is set.
- Added a Gulp task that concatenates the CSS files for all blocks that we have not yet customized for this theme.
- Enqueued the concatencated CSS file as `cata-wp-block-library` and made our blocking CSS depend on it so we can override anything we need.
  - At first glance it seems bad to add another blocking CSS file to all our sites, but we would have to incorporate all this into our main blocking CSS file anyway, so it isn't worse to do it this way.
  - Added gulp-concat dependency since these CSS files were already autoprefixed and everything else, we just needed to combine them.

### CODE REVIEW

**Comment by douglas-johnson** [comment]
@richdacuban This might be a hard review since it's a lot of small changes. Could you please take a look and comment with 1-2 questions about what's changed and why? It would help me make sure I'm thinking critically about all the little bits.

**Comment by richdacuban** [comment]
@douglas-johnson 

Is it not possible for us to support these typography  options in the editor?

> 			"fontWeight": false,
>			"letterSpacing": false,
>			"textDecoration": false,
>			"textTransform": false,

**Comment by douglas-johnson** [comment]
> @douglas-johnson
> 
> Is it not possible for us to support these typography options in the editor?
> 
> > ```
> >   	"fontWeight": false,
> >   	"letterSpacing": false,
> >   	"textDecoration": false,
> >   	"textTransform": false,
> > ```

We could support text transform if we want. Think we should let that one through? Might be useful for the kicker block.

I have issues with the other ones, as follows:

- Font weight is not really possible since you can't define which weights are supported by which fonts. Maybe in a future where variable fonts deliver on the promise of all weights in a single smaller file.
- Letter spacing doesn't really work when you give the editor free reign. Only devs knows to make the spacing `0.125em`, and there's no way to provide named values like you can for font-size.
- I personally thought text-decoration was a weird choice since underline usual denotes a link. Plus it's usually applied to an inline element rather than a whole paragraph or heading.

**Comment by richdacuban** [comment]
> 

All makes sense. re: `Only devs knows to make the spacing 0.125em, and there's no way to provide named values like you can for font-size.` I didn't realize we couldn't name the values.

**Pull request merged**
